<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
<link rel="stylesheet" href="../../../common.css">
<script src="../../../common.js"></script>
<title>3. 自作例外</title>
</head>
<body>

<nav class="brcr">
<ol>
<li><a href="../">アクティビティ: オブジェクト指向プログラミングの基礎</a></li>
<li>学習項目: [2] 例外処理</li>
<li><script>GetTitle()</script></li>
</ol>
</nav>

<h2><script>GetTitle()</script></h2>

<p>
例外クラスを自作して「throw」を使って投げる事も出来ます。
<br>
自作例外クラスの作り方はプログラミング言語によって変わりますが、Java では次のように作ります。
</p>

<div class="info">
<input type="checkbox"><b>ソース1:</b>
<pre class="wrap">
public class MyException extends RuntimeException {

	  MyException(){
		  super("自作した例外です");
	  }	 
}
</pre>
</div>

<p>
ここで出てきた「extends RuntimeException」とか「super」は「継承」のテキストで説明しますので、今の所はこう書くんだ程度の認識でいて下さい。
<br>
またこの自作例外クラスの作り方はかなり簡略化したものですので、実際の業務等で使う場合はちゃんとしたやり方を調べてから作って下さい。
</p>

<p>
後は実行中に何か問題が生じたら、次のように throw 文でこの自作例外をnewして投げて catch で受け取るだけです。
<br>
「throw new MyException();」が自作例外を投げて(throw)している部分です。
</p>

<div class="info">
<input type="checkbox"><b>ソース2:</b>
<pre class="wrap">
     try{ 
         if( 何か問題があったら ) throw new MyException();
     } 
     catch( MyException e ) { 
         System.out.println( e.getMessage() ); 
     } 
</pre>
</div>

<p>
これを実行して何か問題が生じたら「自作した例外です」と表示されます。
</p>

<script>PreNext(3,3)</script>
</body>
</html>
